### PR TITLE
Add Mastodon sharing via toot.kytta.dev

### PR DESCRIPTION
**Pull request by colinleroy**
Hello,

Everyone's fleeing from twitter, so here is a basic PR to enabled Mastodon sharing using toot.kytta.dev.

As you may know, Mastodon is decentralized, so we need to direct the user to their Mastodon instance before sharing. This is what toot.kytta.dev does. 

Another possibility would be to do it locally on the wordpress instance, but it would rather complicate the very clean code of minimal-share-buttons. I don't think this is necessary, as toot.kytta.dev is publically available for this exact purpose.

Hope this helps!

PS: The SVG icon comes from https://www.svgrepo.com/svg/361912/mastodon-simple and is Public Domain, so there should not be redistribution issues.

### CODE REVIEW

**Comment by colinleroy** [comment]
Hi there,
just poking on this, maybe you missed it? Or is the project abandoned?
Thanks!

**Comment by colinleroy** [comment]
ping @gonzomir :)

**Comment by gonzomir** [comment]
Thanks, @colinleroy for this PR and sorry for the loong delay. I didn't get any notifications when you opened it. Merging this and I'll prepare a new release in the coming weeks.

**Comment by colinleroy** [comment]
Thanks @gonzomir !

**Pull request merged**
